/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;

import java.awt.HeadlessException;
import java.awt.List;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author student
 */
public class AddRule extends javax.swing.JFrame {

    /**
     * Creates new form AddRule
     */
    File regulyXML;
    ArrayList<String> objawy;

    public AddRule(String title) throws HeadlessException {
        super(title);
    }

    public AddRule(File regulyXML) {
        this.regulyXML = regulyXML;

        initComponents();
        setVisible(true);
        jTextField2.setText("");
        jTextArea1.setText("");
        objawy = new ArrayList<String>();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Wniosek:");

        jLabel2.setText("Objawy:");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("dodaj objaw");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Dodaj regułe");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Prawdopodobieństwo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jTextField2))))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //dodawanie objawów
        if (jTextField2.getText().length()>1) {

            objawy.add(jTextField2.getText());
            jTextArea1.setText((jTextArea1.getText() + "\r\n" + jTextField2.getText()).trim());
            jTextField2.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Wpisz objaw");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int last = findLastRule(regulyXML);
        String plik = "";
        String regula = "";
        int ruleCount = 1;

        //dopisywanie modelu do pliku
        try (Scanner s = new Scanner(regulyXML)){
            
            System.out.println(plik);
            String linia;
            for (int i = 0; i < last; i++) {
                linia = s.nextLine();
                plik += linia;
                if (linia.contains("</nr>")) {
                    linia=linia.replaceAll("</nr>", "");
                    linia=linia.replaceAll("<nr>", "");
                    ruleCount=Integer.parseInt(linia.trim());
                    ruleCount++;
                }
                plik += "\r\n";
                plik += regula;
            }
            plik += "\r\n";
            s.close();


            System.out.println(plik);
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Nie można odczytać pliku");
            Logger.getLogger(AddModel.class.getName()).log(Level.SEVERE, null, ex);
        }
        //dodanie reguly do stringa
        regula += "  <regula>\r\n";
        regula += "	<nr>" + ruleCount + "</nr>\r\n";
        regula += "	<wniosek>" + jTextField1.getText() + "</wniosek>\r\n";
        regula += "	<objawy>\r\n";
        //dodawanie objawów
        for (String objaw : objawy) {
            regula += "		<objaw>" + objaw + "</objaw>\r\n";
        }
        regula += "	</objawy>\r\n";
        regula += "	<cf>" + jTextField3.getText() + "</cf>\r\n";
        regula += "  </regula>\r\n";
        regula += "</reguly>\r\n";


        plik += regula;

        //dodanie stringa do bnazy
        //System.out.println(plik);
        try {
            FileWriter f = new FileWriter(regulyXML);
            f.write(plik);
            f.close();
            JOptionPane.showMessageDialog(null, "Pomyślnie dodano regułę");
            setVisible(false);
            dispose();
        } catch (IOException ex) {
            Logger.getLogger(AddModel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private int findLastRule(File regulyXML) {// znajdowanie lini ostatniego modelu
        int lastLine = 0;
        try(Scanner s = new Scanner(regulyXML)) {
            
            int i = 0;
            while (s.hasNextLine()) {
                i++;
                if (s.nextLine().contains("</regula>")) {
                    lastLine = i;
                }
            }
            s.close();
        } catch (FileNotFoundException ex) {

            Logger.getLogger(AddModel.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Nie można odczytać pliku");
        }

        return lastLine;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
